### ISSUE TITLE
Mockups based on policy team input

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#15]
@eurolife to determine scope for mockups in sprint

Grouped by [backlog](https://www.notion.so/climatepolicyradar/8f3dfc6ff19c4ead915e342b2f768e4e?v=6f3e235a49984500bf973d7a80962008)?

- [x] Search page
- [x] Search results
  - [x] Search result passages sidebar
  - [x] Search result passage context page
  - [ ] Document cover page
  - [ ] Document viewer
- [ ] Landing page
- [ ] Navigation sidebar
- [ ] User login
- [ ] User account

**Comment by eurolife** [comment]
Figma prototype (still being developed) here: https://www.figma.com/proto/p0yd3uxnoPvpkZXKrbhR0O/Navigator?page-id=8%3A63&node-id=8%3A63&viewport=241%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=35%3A2546

**Comment by kdutia** [comment]
closing based on individual mockup tasks e.g. #46 #47 #48. Landing page and navigation sidebar are post-alpha.
