### ISSUE TITLE
Prepare datasets for World Bank

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#16]
Including:
* policy-level dataset with sector and instrument assignments from CCLW
* passage text level dataset
* passage embeddings

Produce these in a repository with sample notebooks showing how to load the data.

Also double-check with Michal that it's sensible to aggregate sectors and instruments over the policy-level dataset from CCLW.

**Comment by chrisaballard** [comment]
I have put together the following dataset and associated information:

- policy level metadata
- passage level text
- passage embeddings
- sector and instrument taxonomy files
