### ISSUE TITLE
Define scope and objectives for document text extraction

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#20]
e.g.
* section and title extraction
* paragraph blocks (incl. different number of columns), extracted in reading order
* excluding text that's not part of the reading order e.g. headers, footers, sidebars, figure captions
* contents pages, appendices, indexes
* tables
* figures
* anything else in the [PDF layout specification](https://www.adobe.io/apis/documentcloud/dcsdk/docs.html)

Also look at datasets. Could we produce any datasets where we have both the PDF document and HTML (or some markup) representation: maybe eurlex or legislation.gov.uk.

Write a Notion page which summarises this.

**Comment by chrisaballard** [comment]
I have put together a notion page describing the high level scope, objectives and requirements for the research and development of an improved approach to text extraction from policy documents. This will be shared with the team for feedback.
