### ISSUE TITLE
Post-processing of extracted text using heuristics

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#231]
When adding a document to the system, in either the bulk load from CCLW or when adding individual documents, the system should extract the text from that document. Apply heuristic rules to handle the following layout situations:

- Ignoring headers and footers
- Ignoring text in tables and figures including their captions
- Joining hyphenated words which are common in documents
- Lists
- Sentences which have been split into separate passages
- Subscripts/Superscripts

We need to have reviewed the extracted dataset before tackling this task to make sure that we fully understand all the text quality issues.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/231?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by kdutia** [comment]
Closing as broken down into #352 #353 #354 #355 #356 #357
