### ISSUE TITLE
Identify appropriate search index database - literature review

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#232]
Carry out a literature review based on our search requirements to identify candidate search databases.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/232?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by kdutia** [comment]
Initial literature review based on requirements done [on Notion](notion://www.notion.so/climatepolicyradar/Search-index-selection-88d93719bb3f4c6296ea1861923b8474). Opensearch and Vespa chosen as candidate databases to test.
