### ISSUE TITLE
Administrator can view user accounts set up on the system

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#244]
An Administrator can view the user accounts that are set up on the system.

They should be able to view:

- Email address

- Full name

- Affiliation organisation

- Affiliation

- Date when authorised

- Date of last login

<br/>

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Policy-Radar-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/244?planning-poker) with ZenHub @eurolife @ingemar-cpr @kdutia @opyate

**Comment by opyate** [comment]
Backend work for alpha:
- add extra fields to user table (affiliate*, dates)
- limit GET /users listing to admins
