### ISSUE TITLE
Semantic similarity match score between query and passage, summary and title

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#270]
When matching by semantic similarity at passage, summary and title level, a similarity score should be calculated.

This score will be used to rank the relevance of the match to the user’s query.

<br/>

**Comment by kdutia** [comment]
This isn't possible with Opensearch as it [does not normalise relevance scores](https://www.elastic.co/guide/en/elasticsearch/reference/current/consistent-scoring.html). It's something that we could investigate post-alpha if still considered a priority for users.

**Comment by kdutia** [comment]
see also https://github.com/elastic/elasticsearch/issues/23850
