### ISSUE TITLE
Early Access User can reset their password

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#283]
An Early Access user can reset their password if they forget it

The user should be able to click a “Forgot password?” link.

The user should be asked to enter their email address.

If the email address matches an account on the system, Navigator should send the user an email to the email address.

This email should contain a link.

Clicking the link will ask the user to specify a new password on the account creation screen

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Policy-Radar-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/283?planning-poker) with ZenHub @eurolife @ingemar-cpr @kdutia @opyate

**Comment by opyate** [comment]
- request password reset:
  - frontend
  - send email to API
- backend creates unique token, with expiry
- backend sends email (currently, messaging functionality doesn't exist) to user, with a link to frontend, containing unique token
  - messaging service
  - email template (copy, design)
- user clicks on link in email
  - go to frontend
  - frontend checks validity of token, and displays appropriate error
  - if token valid, render form
- user enters new password, and posts form
  - POST to API
  - mark unique token as used
  - set user's new password
  - backend replies with success
- frontend says success
  - redirect to login, and ask user to log in with their new password

**Comment by ingemar-cpr** [comment]
Paula and I agreed on the slight modifications to your proposal above:

1. After the user submits the token and new password, the server will reply with a new JWT token which will result in the user not having to sign in.

Additional note: Front-end shouldn't need to validate the token - it should be done on the server side. If the token has expired, we would simply show an error message.

**Comment by opyate** [comment]
> After the user submits the token and new password, the server will reply with a new JWT token which will result in the user not having to sign in.

Sure, but it seems standard practice to let a user sign in again after choosing a new password. It also allows their password manager to update (as the credentials are usually linked to a particular sign-in page).

> Additional note: Front-end shouldn't need to validate the token - it should be done on the server side

The link in the email goes to the frontend, so it would need to verify it with an API call.
