### ISSUE TITLE
Frontend > user can view Action Cover Page for a search result

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#285]
For a selected search result, the user should be able to open the corresponding Action in order to view all the information held about it.

The “Action cover page” should display:

- Action name e.g. Net Zero Strategy
- Action description - CCLW summary
- Location of publication (geography - e.g. France, United States, Peru etc)
- Action year e.g. 2020
- Action type - either executive or legislative
- Documents contained in the action (#287)

This information should be read-only.

- View Action Cover Page using deep linked URL

---
It should be possible to navigate to an Action cover page using a deep linked URL:

```yaml
/actions/{action_id}
```

This should display the action cover page for the action with id `action_id`

Note:
- The display of metadata, keywords and events are out of scope for this task.

Desktop:
https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2Fp0yd3uxnoPvpkZXKrbhR0O%2FNavigator%3Fpage-id%3D8%253A63%26node-id%3D381%253A11978%26viewport%3D241%252C48%252C0.5%26scaling%3Dscale-down%26starting-point-node-id%3D35%253A2546

Mobile:
https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2Fp0yd3uxnoPvpkZXKrbhR0O%2FNavigator%3Fpage-id%3D279%253A2669%26node-id%3D439%253A8791%26viewport%3D241%252C48%252C0.65%26scaling%3Dscale-down-width%26starting-point-node-id%3D279%253A5267

**Comment by marcusodavies** [comment]
Updated the metadata shown on the action cover page as agreed with @danny-waite-cpr and @eurolife, and as reflected in mockup of action cover page.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/285?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by kdutia** [comment]
@chrisaballard to adjust the scope of this task for the current sprint

**Comment by opyate** [comment]
At a push, we can mock data to get Paula started quickly:
[Mock Servers:](https://openapi.tools/#mock) Fake servers that take description document as input, then route incoming HTTP requests to example responses or dynamically generates examples.
