### ISSUE TITLE
User can view the source of metadata values

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#301]
The user should be able to view the source of metadata values for any metadata filter. This should indicate next to each metadata value the source of that value. For example “CCLW”, “CPD”.

Should the user be able to filter the list of metadata values by a source? E.g. only view metadata values which have been received from CCLW?

<br/>

**Comment by marcusodavies** [comment]
@chrisaballard in response to a question on the Notion backlog for this requirement: agreed with @danny-waite-cpr that displaying and filtering by metadata source is not a priority for the Alpha given that we are only using data from CCWLW - provided that we are storing the metadata source anyway and that it won't be overly complicated to display it at a later stage!
