### ISSUE TITLE
Add code coverage tracking to e2e and backend tests 

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#31]
This should run as part of the github actions workflow. As part of this task we should also see whether it's straightforward to generate a test report - see [comments on the first automated testing PR](https://github.com/climatepolicyradar/navigator/pull/9#pullrequestreview-845956000)

**Comment by opyate** [comment]
Also warn if the coverage dropped, and fail if the coverage is below a threshold.
