### ISSUE TITLE
An Action will be associated with keywords

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#312]
It should be possible to associated an Action with one or more keywords.

The initial list of keywords will be imported from CCLW.

A unique list of keywords will be stored, in order to associate multiple Actions sharing the same keyword.

Keywords will be added to the unique keyword list if a new keyword is entered when initially populating Actions, or a user submits an Action having a new keyword.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Policy-Radar-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/312?planning-poker) with ZenHub @eurolife @ingemar-cpr @kdutia @opyate

**Comment by opyate** [comment]
For alpha: just API and DB changes. No backoffice management.
