### ISSUE TITLE
Extract text from PDF documents using Adobe Extract API

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#335]
The pdf2text cli should use the Adobe Extract API to extract text passages from PDF documents.
Where the document cannot be processed by the API, it should fallback to using the embedded text parser.

The format of the output is described in #346.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/335?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by kdutia** [comment]
@chrisaballard I've just remembered that the Adobe Extract API is [optimised for English and compatible with latin alphabet languages](https://community.adobe.com/t5/document-services-apis-discussions/pdf-extract-api-language-support/m-p/12491903). I think this means that for language detection we'd want to run PDFalto on all docs, then a translator to filter to English, then the Adobe API. 

I'm not saying that all of that is in the scope for this task but this would change the way that this task has defined the pipeline. For now we could just test the pipeline on documents that were identified as English language during the development of the prototype, and then add a language detection stage later. What do you think?
