### ISSUE TITLE
Research embedded PDF viewer options

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#337]
The following stories refer to displaying an embedded PDF with matches highlighted:

- #278
- #279
- #280
- #296

There are a number of embeded PDF viewers we could use for this, but are unsure of the limitations of each and whether they will allow us to meet the requirements stated in the stories.

This task is to research and evaluate the options against these requirements:

- Identify JavaScript components that can be used
- Build a prototype UI for each component which demonstrates
  - highlighting text spans that match
  - etc.

**Comment by opyate** [comment]
Check out https://mozilla.github.io/pdf.js/

**Comment by opyate** [comment]
Perhaps a remaining point here could be to check how we distribute the Adobe plugin with our open source frontend code. It might also depend on the license we go with (e.g. MIT).

**Comment by eurolife** [comment]
I have had a look at 3 potential embedded pdf viewer options: 

**Mozilla PDF.js** - This is an open source project, but I found it very difficult to implement any kind of functionality beyond the basics which is simply loading a pdf file on a specified page and navigating to different pages. I was unable to get the search functionality to work which would involve searching for matching text and highlighting it, and navigating through each instance of the match (if more than one). The documentation was very limited. API docs non-existent. Examples of code hard to find and those that I could find were either hard to implement (parts missing, etc) and mostly resulted in errors which I could not make sense of and could not find solutions to. It also doesn't play nicely with ReactJS.

**PDF Object** - I thought this would be a fully functional independent embed solution, but it really isn't. It simply detects if the browser supports embedded pdf viewers and offers the possibility to show a fallback if it doesn't. The more important functionality would still be dependent on another tool such as PDF.js. 

**Adobe PDF Embed API** - This was by far the best and easiest to implement. It is very well documented [https://developer.adobe.com/document-services/docs/overview/pdf-embed-api](url) and has a lot of very useful code examples: [https://github.com/adobe/pdf-embed-api-samples](url) I was able to implement the search functionality which highlights the search terms and then you can navigate through each instance. The API provides a lot of flexibility with regards to the features we are wanting. The only limitation I found was that it doesn't allow for searching and highlighting more than one set of search terms at one time, but as suggested in my demo, a drop down of different matches within the document could be utilised as a solution to this.
