### ISSUE TITLE
Administrator can manually add new early access user accounts

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#340]
An Administrator should be able to manually add new user accounts to the system.

They should be required to enter the following information:

- Full name
- E-mail
- Re-enter e-mail
- Affiliation/Organisation (also allow ‘personal’)
- Affiliation type - display the following values:
  - Academia
  - Public sector
  - Private sector
  - IGO
  - NGO/not-for-profit organisation
  - Individual
  - Other

The user should enter the same email address in the "Email" and "Re-enter email" fields. If there is a difference between the two, an error should be displayed.

If "Other" is selected, the user should be able to enter a free text affiliation type. This field will be disabled unless "Other" is selected.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Policy-Radar-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/340?planning-poker) with ZenHub @eurolife @ingemar-cpr @kdutia @opyate

**Comment by opyate** [comment]
See #244 about adding new fields.
