### ISSUE TITLE
Pdf2text cli > Process documents in s3 bucket

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#345]
The cli developed in #53 will only process files in a local directory.
It should be possible to specify an inbound s3 bucket and an s3 bucket to place the extracted data.
The documents should be processed in the inbound s3 bucket.
The extracted json and text documents should be placed in the second bucket.

**Comment by chrisaballard** [comment]
Existing code has already been implemented which provides an `S3Client` class:

https://github.com/climatepolicyradar/navigator/blob/c1c5e9431ce85eac42f7f683f18103f61932a31f/backend/app/core/aws.py#L38-L46

This provides an `upload_file` method which can be used to upload the output of `pdf2text` cli, but I will need to implement a similar `download_file` method to pull down files in an input bucket to be processed by the cli.

This code sits in `/backend/app` which is not a package and sits at the same level in the project as `pipeline`. To share this code between the backend and the pipeline some code restructuring is going to be necessary. As I see it, these are the options:

- move `pipeline` into `\backend` at the same level as `\backend\app`. This would involve making `app` a package and the Dockerfile in `\backend` would need to be moved
-

**Comment by opyate** [comment]
As we're using a monorepo, introducing a `common` or `core` would make sense.

**Comment by chrisaballard** [comment]
@opyate @kdutia I've updated the comment above with more specific details about the changes I'm making today to create a common python package outside of `backend` and `pipeline`. I'm proposing to call it `navigator` as it would allow us to deploy it to pypi in future. Are you both happy with that?

**Comment by kdutia** [comment]
@chrisaballard there's a [Navigator](https://pypi.org/project/Navigator/) package on pypi already. How about `cpr-navigator`?

**Comment by chrisaballard** [comment]
The pdf2text cli has been updated to support the processing of pdf documents stored on s3. This can now be used to batch extract text from documents in an s3 bucket, and then upload the extracted json and text files to a second bucket.

There have been some changes to the cli arguments. You no longer need to specify --text or --json`` arguments as this is implicitly assumed. There is a new argument s3` which is used to inform the cli that you wish to process files on s3 rather than locally, and it will interpret the paths as s3 bucket/folder locations.

In this regard, the bucket folder locations are specified in the following format:

[bucket]/[folder]/[folder]/...

It will parse the string to obtain the bucket name and folder path and will read/write files into the corresponding bucket and nested folders.

In addition to this, the codebase has been refactored to introduce a common navigator package in common/navigator. This is now referenced in backend and pipeline and is included in the respective Dockerfiles. This means that any common code can be placed in this package and imported like so:

from navigator.core.aws import S3Client

I have not updated the unit tests for pipeline as all changes have been made to the pdf2text cli script rather than package/module code. I think later we may well want to put this code into separate modules, at which point unit tests could be created. But I think its worthwhile incorporating the Adobe API changes first to see what impact this has.
