### ISSUE TITLE
Pdf2text cli > Nest text blocks inside pages and support for polygon text blocks

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#346]
The cli developed in #53 only stores the overall page dimensions of the final page. Since some pdfs could contain pages with different dimensions, it is important to be able to store size per page.

Change the output json structure to nest each text block inside the page in which it is contained.
Against each page, record the dimensions of that page
Currently, each textblock can only store 4 coordinates for a rectangular text block. Since OCR can output polygons, adapt it so that a list of multiple coordinates can be stored for each text block.

**Comment by kdutia** [comment]
@chrisaballard for `Page`, why does the dimensions property not just have type `Tuple[float, float]`?

Also, I'll likely extend the `TextBlock` class to support some of the richer outputs from Adobe e.g. document layout types. Do you think it'd be best to do this by adding `Optional` properties to the `TextBlock` class or creating a new `AdobeExtractTextBlock` class that inherits from `TextBlock`? 

I'm thinking the former, as any code written that uses `TextBlock` will be written to accommodate these extra properties.

**Comment by chrisaballard** [comment]
@kdutia page dimensions could have been a float tuple. I decided to add a dataclass for it to distinguish between x and y coordinates, especially when outputting json. But in hindsight this may have over-engineered it - I'll take a look at this.

I agree, lets add attribues to `TextBlock`. Are you able to provide details of them, or do you want to do as part of the scope of #335?

**Comment by chrisaballard** [comment]
I have made the changes proposed in the comments above, including changing the `Page` dimensions and `TextBlock` coords over to `List[Tuple[float]]` as @kdutia proposed.

Following testing, I noticed that each of the lines in a text block were being concatenated with a space. This meant that cases such as word hyphenation would include a space between the hyphen at the end of the line and rest of the word in the following line - e.g. `correct- ted`. This will make post-processing more difficult to remove those cases.

To address this, I have changed `TextBlock` to store a list of lines in each text block. This will make post-processing much easier because hyphenated words can be dealt with my merging a word where the final character at the end of a line is a hyphen with the first word in the next line (at least that would be the baseline way to do it). This new structure is reflected in the json. There are also new `to_string()` methods on `TextBlock` and `Page` to handle concentation of lines and text blocks in a page respectively.

Note that the text file output using the `--text` argument on the cli will continues to merge all lines in a text block with a space so will look the same.

**Comment by chrisaballard** [comment]
I have merged the latest changes in `dev` into the branch for this change to make sure the unit tests defined by Kalyan are included. Final step is to double check that the unit tests are still valid following the changes I have made and whether additional tests need to be added.
