### ISSUE TITLE
Use cli to run text extraction for CCLW corpus using Adobe Extract API and Embedded Text parser

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#348]
Use the pdf2text cli to extract the text from the english language PDFs in the CCLW corpus and generate the json output files in an s3 bucket. This will create a dataset which will allow us to progress with search and ETL of text data.

- [x] make a list of PDFs from english language CCLW, based on analysis from prototype
- [x] run these through the extract pipeline
- [x] when postprocessing done, rerun `data_to_document` step on all intermediate files

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/348?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by kdutia** [comment]
@ingemar-cpr @stefl14 and I talked about doing a one-off data cleaning exercise for CCLW to get the document title from each PDF. Before doing this data load we should check that the data is suitable for this.

**Comment by kdutia** [comment]
I emailed adobe today regarding outstanding BAD_PDF and 500 errors, and the timeout and variable page splitting limit issues we were having.
