### ISSUE TITLE
Post-processing of extracted text > Ignoring headers and footers

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#352]

**Comment by kdutia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/352?planning-poker) with ZenHub @opyate @chrisaballard

**Comment by stefl14** [comment]
* Repeated headers and footers on every page.
* This one is just a matter of checking, if not come up with heuristic for error cases.
