### ISSUE TITLE
Post-processing of extracted text > Ignoring text in tables and figures

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#353]
including titles and captions

**Comment by kdutia** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/353?planning-poker) with ZenHub @opyate @chrisaballard

**Comment by stefl14** [comment]
Looks to me like this is a stale issue. Adobe does this automatically and I couldn't find any error cases running the embedded text extractor on a bunch of documents.
