### ISSUE TITLE
Post-processing of extracted text > Joining hyphenated words which are common in documents

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#354]
Often, words will be broken by a hyphen to wrap them into a column. These breaking hyphens would need to be detected, removed and the two parts of the word joined together. Note that distinguishing them from valid occurrences such as a bullet point (see above) may be tricky.

Example:

![image.png](https://images.zenhubusercontent.com/613642a341f39720ef8348ee/1b726946-5b25-4501-9829-b6296c910037)

> The  national  effort  to  draw  and  execute strategic  plans  will  benefit  from  financial contribution  of  the  international  communi- ty.  It  will  be  necessary  to  create  conditions so  that  potential  support  is  converted  into actual  support.  For  that  purpose  the administration  shall: –  Establish  a  forest  fund  to  channel  inter- national  funds  meant  for  the  support  of the  implementation  of  this  forest  policy. –  Promote  the  financing  of  capacity  build- ing  and  investments  to  the  private  sec- tor  by  development  banks

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Policy-Radar-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/354?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by opyate** [comment]
Bullet points seem to use m-dash, and hyphenated words a dash. ([difference](https://www.punctuationmatters.com/en-dash-em-dash-hyphen/))
