### ISSUE TITLE
Post-processing of extracted text > structure lists

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#355]
When viewing search result passages, a user should be able to see bullet lists displayed as individual list items. Currently they may be displayed as part of a textblock.

This could be done using the Adobe Extract API.

Example:

![image.png](https://images.zenhubusercontent.com/613642a341f39720ef8348ee/63d1c4fe-471b-4247-9811-b6d3a90e547a)

> Implementation  of  this  forest  policy requires  further  elaboration.  The  continua- tion  will  be  closely  monitored  and  the  for- est  policy  itself  will  be  periodically  evaluat- ed  and,  where  necessary,  adapted.  This means: –  Elaboration  of  action  items  in  strategic plans  and  their  execution –  Monitoring  of  the  progress  of  the  imple- mentation  of  this  policy

> Implementation  of  this  forest  policy requires  further  elaboration.  The  continuation  will  be  closely  monitored  and  the  forest  policy  itself  will  be  periodically  evaluated  and,  where  necessary,  adapted.  This means:
> –  Elaboration  of  action  items  in  strategic plans  and  their  execution
> –  Monitoring  of  the  progress  of  the  imple- mentation  of  this  policy

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Policy-Radar-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/355?planning-poker) with ZenHub @eurolife @kdutia @opyate
