### ISSUE TITLE
Post-processing of extracted text > Sentences which have been split into separate passages

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#356]
Where a sentence or paragraph spans more than one page, it will be considered to be an independent text block by the parser. This will result in the last sentence in the first text block being truncated, and the first sentence in the second text block starting in the middle of the sentence. See previous example.

Passages may be broken across multiple text blocks, depending on the layout of the document. These text blocks would need to be merged to ensure that they contain meaningful passages. For example, in the following the parser has correctly retained the correct natural reading order, but these have been parsed into separate lines.

Options:
- Consider for alpha the impact of just displaying, rather than resolving, these breaks on a user viewing the full text and search.
- Store metadata at passage level which could be use to control how passages that are broken across pages/columns are displayed.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Policy-Radar-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/356?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by opyate** [comment]
Another idea I floated in the sprint meeting: if we have the bounding box of the passage, take a PNG snapshot of the PDF at those coordinates, and render the PNG on the website (instead of the entire PDF, or cleaned-up text).

**Comment by kdutia** [comment]
The [Adobe Extract API](https://developer.adobe.com/document-services/docs/overview/pdf-extract-api/howtos/extract-api/) returns a paragraphSpan element when it predicts a paragraph is split over pages or columns. We should measure the extent to which this solves this issue.
