### ISSUE TITLE
Technical > Review structure of navigator project

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#40]
Review the structure and organisation of the navigator project.
For example:
- Security implementation
- Use and implementation of FastAPI and handling of routes
- Service documentation
- Storing project documentation - e.g. specifications

**Comment by opyate** [comment]
Notes WIP here https://www.notion.so/climatepolicyradar/Tech-notes-c57f4e9954aa465883bdf0db76397ab6

It covers a bit more than the structure of the navigator project, though.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/40?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by opyate** [comment]
The structure as it stands is OK, and will evolve over time.
I like having frontend and backend together in a mono-repo, as it ensures that the code works together at any given commit.

**Comment by opyate** [comment]
Documentation refactored in #339

**Comment by chrisaballard** [comment]
Reviewed PR #339 - all looks good. Moving to Done.
