### ISSUE TITLE
Implement the Auth flow in front-end

### ISSUE THREAD

**Issue by ingemar-cpr** [climatepolicyradar/navigator#406]
Early access user creates account, specifying email and password
======================
The Early Access user should provide the following additional information to create their account:

- Password - masked text field
- Confirm password - masked text field
- The user should enter a password. This should conform to strong password standards.
- The user should re-enter their password in the confirm password textbox.
- They should click a button to submit their account details.
- After submitting, the user should be logged in and redirected to the home page.
- An email address should be given for them to contact CPR in the event of any concerns or questions or don’t receive the email.

Early access user enters email address and password to login
================

Reset password
==============
An Early Access user can reset their password if they forget it
The user should be able to click a “Forgot password?” link.
The user should be asked to enter their email address.
If the email address matches an account on the system, Navigator should send the user an email to the email address.
This email should contain a link.
Clicking the link will ask the user to specify a new password on the account creation screen

Sign Out
================
User can click button to log out

**Comment by ingemar-cpr** [comment]
From Juan:

request password reset:
frontend
send email to API
backend creates unique token, with expiry
backend sends email (currently, messaging functionality doesn't exist) to user, with a link to frontend, containing unique token
messaging service
email template (copy, design)
user clicks on link in email
go to frontend
frontend checks validity of token, and displays appropriate error
if token valid, render form
user enters new password, and posts form
POST to API
mark unique token as used
set user's new password
backend replies with success
frontend says success
redirect to login, and ask user to log in with their new password

**Comment by ingemar-cpr** [comment]
Paula and I agreed on the slight modifications to your proposal above:

After the user submits the token and new password, the server will reply with a new JWT token which will result in the user not having to sign in.
Additional note: Front-end shouldn't need to validate the token - it should be done on the server side. If the token has expired, we would simply show an error message.

**Comment by ingemar-cpr** [comment]
Reply from Juan:

After the user submits the token and new password, the server will reply with a new JWT token which will result in the user not having to sign in.

Sure, but it seems standard practice to let a user sign in again after choosing a new password. It also allows their password manager to update (as the credentials are usually linked to a particular sign-in page).

Additional note: Front-end shouldn't need to validate the token - it should be done on the server side

The link in the email goes to the frontend, so it would need to verify it with an API call.

**Comment by eurolife** [comment]
@ingemar-cpr I think @opyate made a good point about the password manager being able to update, (like Chrome or other password managers). I hadn't thought of that. So maybe the user signing in again after change of password is preferred after all.

**Comment by eurolife** [comment]
This is partly implemented, just waiting on backend functionality (email triggering) and new api endpoints.
