### ISSUE TITLE
Implement Account functionality in front-end

### ISSUE THREAD

**Issue by ingemar-cpr** [climatepolicyradar/navigator#407]
Logged in users will be able to view an Account page allowing them to view and update their account details:

This should display a page containing the following information:

- Name
- Email
- Affiliation
- Affiliation type
- Password

Password will not be populated, but is used to allow them to update their password if needed.

Update Email
==============

- If the user updates their email address, the new address should be verified.
- Navigator will send the user an email to the new email address. This email will contain a unique link for that user. This link will expire after a defined period of time (tbc).
- The user should click the link to confirm that their email address is genuine.
- After clicking the link, the email address change will be confirmed.

Update Password
=================

- On the Account Information page, the user will be able to update their password.
- To do this, the user should enter their current password.
- They should also enter a new password, and re-enter the same password.
- This password should conform to strong password requirements.
- The password will be updated only if their current password is correct.

**Comment by eurolife** [comment]
This is partly implemented, just waiting on backend functionality (email triggering) and new api endpoints.
