### ISSUE TITLE
Add additional filtering to search - backend

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#437]
This is raised separately to #420 as at the time of doing that issue, world bank region wasn't in the database.

**Comment by joel-wright** [comment]
@ingemar-cpr final list of required filters to be added here

**Comment by joel-wright** [comment]
@ingemar-cpr I'm not clear on what "Topic" means here

**Comment by ingemar-cpr** [comment]
Michal requested us to remap Themes to Topics
