### ISSUE TITLE
Technical > Docstring standards and documentation

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#44]
Only brief docstrings have been put in place in the current codebase.
During the review of the navigator project, add docstrings.
A number of standards are available. We should probably use one that allows automatic generation of documentation for open source components of the codebase.

Also look up linter that can be used to check docstring format.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/44?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by opyate** [comment]
Looks great! Are we hooking [pep-257](https://www.python.org/dev/peps/pep-0257/) into our pre-commit hooks?

**Comment by kdutia** [comment]
Looks good to me. I've used the [autoDocstring](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) extension for vscode for a few years now, which generates google format docstrings automatically for a function or class. We might want to add this to the Coding standards page too? It also adds types to the args and returned data from a method (which can be disabled), but I don't think these are massively important to us if we are adding type annotations to functions and classes.

@opyate - it seems like [pydocstyle](http://www.pydocstyle.org/en/6.1.1/usage.html#usage-with-the-pre-commit-git-hooks-framework) might be a good candidate for a pep-257 pre-commit hook. I've never used it - what do you think?

**Comment by opyate** [comment]
@kdutia cool, leave it with me. I'll put it in with my next PR. (And potentially isort, bandit, safety, etc)

**Comment by chrisaballard** [comment]
Thanks for reviewing guys, pleased we've come to a consensus on it. I've not come across that extension before, good call @kdutia. Thanks @opyate for sorting out the inclusion of pydocstyle into precommit hooks. I'll move this issue to Done.
