### ISSUE TITLE
Add S3 PDF URL to search endpoint response

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#448]
This is so we can provide the URL to the download PDF button and also the PDF embed viewer using the same API call that was used for search.

Name of the PDF to be uploaded to S3 should be:
https://www.notion.so/climatepolicyradar/Document-names-on-S3-6f3cd748c96141d3b714a95b42842aeb

**Comment by opyate** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html

**Comment by opyate** [comment]
Logs tied to user accounts might need a route through the API instead of directly to the bucket.

**Comment by opyate** [comment]
Or, have a doc API which just responds with a redirect to the public bucket.
