### ISSUE TITLE
Create SendGrid account and configure templates

### ISSUE THREAD

**Issue by ingemar-cpr** [climatepolicyradar/navigator#455]

**Comment by joel-wright** [comment]
@ingemar-cpr I don't seem to be able to find the email templates, are they somewhere in sendgrid or just text saved somewhere else at the moment?

**Comment by ingemar-cpr** [comment]
Activate email
Id: d-b3be8dbb3946456da225a02e0081087a
Params: 
- name
- link

Password Reset email
Id: d-85d7a1be19bb40bea2d80783fe2d1be3
Params:
- name
- link

Password Reset Confirmation email:
Id: d-c83af83f157d4bf6af82d8cbbce386e8
Params:
- name
