### ISSUE TITLE
Implement Structured Logging & Incident Triage

### ISSUE THREAD

**Issue by joel-wright** [climatepolicyradar/navigator#460]

**Comment by opyate** [comment]
Notes captured here: https://www.notion.so/climatepolicyradar/Tech-notes-c57f4e9954aa465883bdf0db76397ab6

Repeating here:
- correlation IDs everywhere (I contributed [[Kong’s correlation-id plugin](https://docs.konghq.com/hub/kong-inc/correlation-id/)](https://docs.konghq.com/hub/kong-inc/correlation-id/), but can make a similar Lua plugin for vanilla nginx)
- e.g. sentry/airbrake for errors
- ELK for req/resp etc
- sanitise
- structured logging is a must (for ease of querying logs)
