### ISSUE TITLE
UI > Mockup > Action cover page

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#47]
Design a figma mockup for the Action Cover page which should include the following components:

- Cover page
- Document list
- Metadata display
- Event timeline

User should see on this page:

- Action name e.g. Net Zero Strategy
- Action description - basically the CCLW summary
- Location of publication (which is basically geography - so, e.g. France, United States, Peru etc)
- Action year e.g. 2020
- Action type - either executive or legislative
- Sector e.g. energy, transport etc
- Instrument e.g. taxes, subsidies etc
- Events e.g. published 2020, amended 2021, replaced 2022
- Keywords e.g. carbon trading, electric vehicles etc
- Theme e.g. mitigation, adaptation etc
- Documents contained in the action
- Indicate source: sector, instrument, keyword, theme, and events should be shown to be from a particular source

**Comment by eurolife** [comment]
Mockup can be viewed at https://www.figma.com/file/p0yd3uxnoPvpkZXKrbhR0O/Navigator?node-id=381%3A11978

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/47?planning-poker) with ZenHub @eurolife @kdutia @opyate
