### ISSUE TITLE
Action search (non-functional UI) > User can enter document search query 

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#51]
The user should be able to enter a search query in a textbox displayed on the search page. They should be able to enter a textual search query of any length.

Before they have entered anything, the textbox should display the text “*Search for something, e.g. ‘carbon taxes’”.*

When the user starts to enter their search query, this text should be hidden.

If the user clears out their search query, this text should be displayed again.

Notes:

- User does not see default list of date-ordered policy documents as in prototype
- User does not yet see filters to the side of search bar
- Search bar contains invitation to begin search, e.g.:
    - *Search for something, e.g. ‘carbon taxes’*

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/51?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by eurolife** [comment]
PR created for this task at https://github.com/climatepolicyradar/navigator/pull/343

- User can enter a search term
- When a search term is entered, an 'X' button is visible to allow the user to clear the search input if needed
- User can click the 'X' button to clear search input
- Pressing enter or the 'Go' button will trigger a search but at this time, this is not functional.
- This page is responsive and works on all screen sizes.

STILL TODO: Write unit tests for this new page.

**Comment by chrisaballard** [comment]
Added issue to implement unit tests in #344
