### ISSUE TITLE
Document processing > evaluate PDF text extraction using OCR

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/navigator#52]
Evaluate OCR as an approach to extracting text from PDF documents.

- Identify candidate OCR tools (e.g. Google CloudVision, AWS)
- Process an image of each page through OCR
- Review identified text blocks and how effective they are at segmenting text into paragraphs and passages
- Understand what heuristics would be needed to post-process the output to remove headers/footers
- Estimate costs of approach
- Compare quality of output to baseline pdf parser

Also measure:
- robustness to noise and distortion
- robustness to different page types (slides/non-white background)

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/52?planning-poker) with ZenHub @eurolife @kdutia @opyate

**Comment by kdutia** [comment]
done - see [notion page](https://www.notion.so/climatepolicyradar/Evaluating-OCR-methods-1841bac54f874469b9670afed3e63f34)
