### ISSUE TITLE
fix CORS on ElasticBeanstalk

### ISSUE THREAD

**Issue by opyate** [climatepolicyradar/navigator#522]
CORS might need to be tweaked in a few places:
- [API code](https://github.com/climatepolicyradar/navigator/blob/dev/backend/app/main.py#L33) (add the new domains Ingemar set up on Cloudflare)
- maybe on AWS (load balancers, or nginx)

**Comment by eurolife** [comment]
@opyate might need to add localhost as well

**Comment by opyate** [comment]
Consulting https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/

**Comment by opyate** [comment]
Opening up CORS on nginx: https://enable-cors.org/server_nginx.html

**Comment by opyate** [comment]
CORS header comes through twice:

![image](https://user-images.githubusercontent.com/96808/168375973-c3e06089-d170-4492-87fa-fcbdd92950fb.png)

![image](https://user-images.githubusercontent.com/96808/168376055-baf81464-0d11-45f1-8bea-615d395222b3.png)


...but when I remove all these lines in [this PR](https://github.com/climatepolicyradar/navigator/pull/566/files):

```
add_header 'Access-Control-Allow-Origin' '$http_origin';
```

... then this header doesn't appear at all.
