### ISSUE TITLE
Review user signup and login process

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#55]
At the moment there isn't a clear distinction between the 'sign up for early access' process on the website and the future signup and login process for the alpha product. 

Have a meeting to decide what the best next steps are.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/55?planning-poker) with ZenHub @eurolife @kdutia @opyate
