### ISSUE TITLE
UI > Mockup > Document viewer

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#56]
Related to the 'Action Document Viewer' column in the [Notion backlog](notion://www.notion.so/climatepolicyradar/8f3dfc6ff19c4ead915e342b2f768e4e?v=6f3e235a49984500bf973d7a80962008).

open full document viewer from document link in action cover page
in passage view in panel, toggle text with pdf view and include option to open in new tab

**Comment by eurolife** [comment]
@chrisaballard I think we will need to have a design meeting to discuss this further before I can start on it. I've read through the stories for this and there is a lot that isn't clear. There is also the question of what is and what isn't possible, especially within alpha.

**Comment by chrisaballard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Tech-Team-613867967a1a9200123c9aad/issues/climatepolicyradar/navigator/56?planning-poker) with ZenHub @eurolife @kdutia @opyate
