### ISSUE TITLE
Associated Documents issues on cover page

### ISSUE THREAD

**Issue by joel-wright** [climatepolicyradar/navigator#592]
1) Associated documents always seem to have a country of United States, even thought he correct information is returned in the document detail API request.

e.g. incorrect associated country: https://app.climatepolicyradar.org/document/95

2) Selecting an associated document changes the URL, but I have to hit reload (on Firefox) to see the updated cover page

**Comment by eurolife** [comment]
@joel-wright I think these things are fixed from my earlier update today.
