### ISSUE TITLE
Slideout Bugs & Enhancements

### ISSUE THREAD

**Issue by ingemar-cpr** [climatepolicyradar/navigator#625]
- [x] - Ideally address ASAP: pdf view takes to page 1 and not to right page in pdf view
- [x] - Ideally address ASAP: slide out should close if anyone does anything else on page e,g filters
- [ ] - Ideally address ASAP: slideout menu (vertical 3 dots) not intuitive

**Comment by eurolife** [comment]
Will need more feedback/ideas on the menu
